-- MySQL Script generated by MySQL Workbench
-- Fri May 12 15:32:28 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema KelenFIla
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema KelenFIla
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `KelenFIla` DEFAULT CHARACTER SET utf8 ;
USE `KelenFIla` ;

-- -----------------------------------------------------
-- Table `KelenFIla`.`voiePaiement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KelenFIla`.`voiePaiement` (
  `idvoiePaiement` INT NOT NULL AUTO_INCREMENT,
  `libellePaiement` VARCHAR(45) NULL,
  PRIMARY KEY (`idvoiePaiement`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KelenFIla`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KelenFIla`.`user` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `emailUser` VARCHAR(100) NOT NULL,
  `numeroUser` VARCHAR(25) NOT NULL,
  `dateInscription` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `password` VARCHAR(100) NOT NULL,
  `typeUser` VARCHAR(45) NOT NULL,
  `pays` VARCHAR(45) NOT NULL,
  `ville` VARCHAR(45) NOT NULL,
  `adresse` VARCHAR(100) NOT NULL,
  `logo` VARCHAR(400) NULL,
  `isActived` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KelenFIla`.`moyenPaiement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KelenFIla`.`moyenPaiement` (
  `idVoiePaiement` INT NOT NULL,
  `idUser` INT NOT NULL,
  PRIMARY KEY (`idVoiePaiement`, `idUser`),
  INDEX `FK_PAIEMENT_USER_MET_idx` (`idUser`),
  CONSTRAINT `FK_PAIEMENT_USER_MET`
    FOREIGN KEY (`idUser`)
    REFERENCES `KelenFIla`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_TYPE_PAIEMENT`
    FOREIGN KEY (`idVoiePaiement`)
    REFERENCES `KelenFIla`.`voiePaiement` (`idvoiePaiement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KelenFIla`.`particulier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KelenFIla`.`particulier` (
  `idParticu` INT NOT NULL,
  `nomParticul` VARCHAR(45) NOT NULL,
  `prenomParticul` VARCHAR(45) NOT NULL,
  `dateNaissance` VARCHAR(45) NOT NULL,
  `idUser` INT(45) NULL,
  `CNI` VARCHAR(400) NOT NULL COMMENT 'carte nationnal d\'identité ',
  `isConfirmed` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`idParticu`),
  UNIQUE INDEX `idUser_UNIQUE` (`idUser`) ,
  CONSTRAINT `FK_CLIENT_USER`
    FOREIGN KEY (`idUser`)
    REFERENCES `KelenFIla`.`user` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KelenFIla`.`entreprise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KelenFIla`.`entreprise` (
  `idEntreprise` INT NOT NULL AUTO_INCREMENT,
  `designEntreprise` VARCHAR(45) NOT NULL,
  `IDU` VARCHAR(45) NOT NULL COMMENT 'numero d\'identification unique d\'entreprise ',
  `nom_intermediaire` VARCHAR(45) NOT NULL,
  `prenom_intermediaire` VARCHAR(45) NOT NULL,
  `poste_intermediaire` VARCHAR(45) NOT NULL,
  `idUser` INT NULL,
  `registreCommerce` VARCHAR(400) NULL,
  `declarationFiscale` VARCHAR(400) NULL,
  PRIMARY KEY (`idEntreprise`),
  UNIQUE INDEX `IDU_UNIQUE` (`IDU`) ,
  UNIQUE INDEX `idUser_UNIQUE` (`idUser`) ,
  CONSTRAINT `FK_ENTREPRISE_USER`
    FOREIGN KEY (`idUser`)
    REFERENCES `KelenFIla`.`user` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KelenFIla`.`categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KelenFIla`.`categorie` (
  `idCategorie` INT NOT NULL,
  `designCategorie` VARCHAR(45) NOT NULL,
  `imageCategorie` VARCHAR(400) NULL,
  `descriptCategorie` TEXT NULL,
  PRIMARY KEY (`idCategorie`),
  UNIQUE INDEX `designCategorie_UNIQUE` (`designCategorie`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KelenFIla`.`enchere`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KelenFIla`.`enchere` (
  `idEnchere` INT NOT NULL AUTO_INCREMENT,
  `numEnchere` VARCHAR(45) NOT NULL,
  ` dateEnchere` DATETIME NULL,
  `durerEnchere` VARCHAR(45) NULL,
  `idCategorie` INT NOT NULL,
  `idVendeur` INT NOT NULL,
  `dateAjoutEnchere` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idEnchere`),
  UNIQUE INDEX `numEnchere_UNIQUE` (`numEnchere`) ,
  INDEX `FK_ENCHERE_CATEGORIE_idx` (`idCategorie`) ,
  CONSTRAINT `FK_ENCHERE_CATEGORIE`
    FOREIGN KEY (`idCategorie`)
    REFERENCES `KelenFIla`.`categorie` (`idCategorie`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_ENCHERE_VENDEUR`
    FOREIGN KEY (`idVendeur`)
    REFERENCES `KelenFIla`.`user` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KelenFIla`.`lot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KelenFIla`.`lot` (
  `idLot` INT NOT NULL AUTO_INCREMENT,
  `designLot` VARCHAR(45) NOT NULL,
  `descriptionLot` TEXT(600) NOT NULL,
  `etatLot` VARCHAR(50) NOT NULL,
  `estimatLot` DOUBLE NOT NULL,
  `numeroLot` INT NOT NULL,
  `image1` VARCHAR(400) NOT NULL,
  `image2` VARCHAR(400) NOT NULL,
  `image3` VARCHAR(400) NOT NULL,
  `image4` VARCHAR(400) NOT NULL,
  `image5` VARCHAR(400) NULL,
  `image6` VARCHAR(400) NULL,
  `isVendue` TINYINT NULL,
  `prixVendue` DOUBLE NULL,
  `idEnchere` INT NULL,
  PRIMARY KEY (`idLot`),
  UNIQUE INDEX `idEnchere_UNIQUE` (`idEnchere`) ,
  CONSTRAINT `FK_LOT_ENCHERE`
    FOREIGN KEY (`idEnchere`)
    REFERENCES `KelenFIla`.`enchere` (`idEnchere`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KelenFIla`.`modalite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KelenFIla`.`modalite` (
  `idModal` INT NOT NULL AUTO_INCREMENT,
  `modalPaiement` TEXT NOT NULL,
  `modalLivraison` TEXT NOT NULL,
  `formuleSalutation` TEXT NULL,
  `modalAutre` TEXT NULL,
  `idUser` INT NULL,
  `delaiPaiement` DATE NULL,
  PRIMARY KEY (`idModal`),
  UNIQUE INDEX `idUser_UNIQUE` (`idUser`) ,
  CONSTRAINT `FK_MODALITE_USER`
    FOREIGN KEY (`idUser`)
    REFERENCES `KelenFIla`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KelenFIla`.`participer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KelenFIla`.`participer` (
  `idUser_client` INT NOT NULL,
  `idEnchere_enchere` INT NOT NULL,
  `isSpectateur` TINYINT NOT NULL,
  PRIMARY KEY (`idUser_client`, `idEnchere_enchere`),
  INDEX `fk_user_has_enchere_enchere1_idx` (`idEnchere_enchere`) ,
  INDEX `fk_user_has_enchere_user1_idx` (`idUser_client`) ,
  CONSTRAINT `fk_user_has_enchere_user1`
    FOREIGN KEY (`idUser_client`)
    REFERENCES `KelenFIla`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_enchere_enchere1`
    FOREIGN KEY (`idEnchere_enchere`)
    REFERENCES `KelenFIla`.`enchere` (`idEnchere`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KelenFIla`.`adjudicataire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KelenFIla`.`adjudicataire` (
  `idAdjud` INT NOT NULL,
  `idLot` INT NOT NULL,
  `prix` DOUBLE NOT NULL,
  `dateVictoire` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `place_adju` INT NOT NULL,
  PRIMARY KEY (`idAdjud`, `idLot`),
  INDEX `fk_user_has_lot_lot1_idx` (`idLot`) ,
  INDEX `fk_user_has_lot_user1_idx` (`idAdjud`) ,
  CONSTRAINT `fk_user_has_lot_user1`
    FOREIGN KEY (`idAdjud`)
    REFERENCES `KelenFIla`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_lot_lot1`
    FOREIGN KEY (`idLot`)
    REFERENCES `KelenFIla`.`lot` (`idLot`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KelenFIla`.`paypal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KelenFIla`.`paypal` (
  `idPayPal` INT NOT NULL AUTO_INCREMENT,
  `emailPayPal` VARCHAR(255) NULL,
  `idvoiePaiment` INT NULL,
  PRIMARY KEY (`idPayPal`),
  INDEX `id_voiePaiment_idx` (`idvoiePaiment`),
  CONSTRAINT `id_voiePaiment`
    FOREIGN KEY (`idvoiePaiment`)
    REFERENCES `KelenFIla`.`voiePaiement` (`idvoiePaiement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KelenFIla`.`bancaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KelenFIla`.`bancaire` (
  `idbancaire` INT NOT NULL AUTO_INCREMENT,
  `nomBanque` VARCHAR(45) NOT NULL,
  `adresseBanque` VARCHAR(100) NOT NULL,
  `numeroCompte` VARCHAR(45) NOT NULL,
  `codeBic` VARCHAR(45) NOT NULL,
  `idvoiePaiement` INT NULL,
  PRIMARY KEY (`idbancaire`),
  INDEX `voiePaiment_idx` (`idvoiePaiement`),
  CONSTRAINT `voiePaiment`
    FOREIGN KEY (`idvoiePaiement`)
    REFERENCES `KelenFIla`.`voiePaiement` (`idvoiePaiement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KelenFIla`.`paiement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KelenFIla`.`paiement` (
  `idUser` INT NOT NULL,
  `idLot` INT NOT NULL,
  `idvoiePaiement` INT NOT NULL,
  `sommePayed` VARCHAR(50) NOT NULL,
  `datePaiment` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idUser`, `idLot`),
  INDEX `FK_paiement_user_idx` (`idUser`),
  INDEX `FK_paiement_lot_idx` (`idLot`),
  INDEX `FK_paiementVoiePaiement_idx` (`idvoiePaiement`) ,
  CONSTRAINT `FK_paiement_user`
    FOREIGN KEY (`idUser`)
    REFERENCES `KelenFIla`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_paiement_lot`
    FOREIGN KEY (`idLot`)
    REFERENCES `KelenFIla`.`lot` (`idLot`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_paiementVoiePaiement`
    FOREIGN KEY (`idvoiePaiement`)
    REFERENCES `KelenFIla`.`voiePaiement` (`idvoiePaiement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KelenFIla`.`commissairePriseur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KelenFIla`.`commissairePriseur` (
  `idComPri` INT NOT NULL AUTO_INCREMENT,
  `nomComPr` VARCHAR(45) NOT NULL,
  `prenomComPri` VARCHAR(45) NOT NULL,
  `CNI_FILE` VARCHAR(400) NULL,
  `idUser` INT NULL,
  PRIMARY KEY (`idComPri`),
  INDEX `FK_comPri_user_idx` (`idUser`) ,
  CONSTRAINT `FK_comPri_user`
    FOREIGN KEY (`idUser`)
    REFERENCES `KelenFIla`.`user` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
